"""initial_migration

Revision ID: 0001
Revises: 
Create Date: 2026-07-04 15:12:55.728297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('seniority_years', sa.Float(), nullable=False),
    sa.Column('max_capacity_per_sprint', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('testables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('app', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('testable_type', sa.Enum('story', 'defect', name='testable_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', 'P4', name='priority_enum'), nullable=False),
    sa.Column('build_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('unassigned', 'assigned', 'in_progress', 'completed', 'blocked', name='status_enum'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('testable_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('ranked_candidates_payload', JSONB(astext_type=Text()), nullable=True),
    sa.Column('overridden_by', sa.Uuid(), nullable=True),
    sa.Column('overridden_reasoning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['testable_id'], ['testables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('testable_id', sa.Uuid(), nullable=False),
    sa.Column('team_member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('developer', 'tester', name='role_enum'), nullable=False),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['testable_id'], ['testables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_history')
    op.drop_table('assignment_history')
    op.drop_table('testables')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('teams')
    # ### end Alembic commands ###
