"""testables_id_type_change

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-06 14:11:34.569977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first
    op.drop_constraint('assignment_history_testable_id_fkey', 'assignment_history', type_='foreignkey')
    op.drop_constraint('dev_history_testable_id_fkey', 'dev_history', type_='foreignkey')

    op.add_column('assignment_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('assignment_history', 'testable_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=15),
               existing_nullable=False,
               postgresql_using='testable_id::varchar')
    op.alter_column('assignment_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('dev_history', 'testable_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=15),
               existing_nullable=False,
               postgresql_using='testable_id::varchar')
    op.add_column('testables', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('testables', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=15),
               comment='Unique identifier for the testable, start with STRY | DEF',
               existing_nullable=False,
               postgresql_using='id::varchar')
    op.alter_column('testables', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
               
    # Recreate foreign keys
    op.create_foreign_key('assignment_history_testable_id_fkey', 'assignment_history', 'testables', ['testable_id'], ['id'])
    op.create_foreign_key('dev_history_testable_id_fkey', 'dev_history', 'testables', ['testable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys first
    op.drop_constraint('assignment_history_testable_id_fkey', 'assignment_history', type_='foreignkey')
    op.drop_constraint('dev_history_testable_id_fkey', 'dev_history', type_='foreignkey')

    op.alter_column('testables', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('testables', 'id',
               existing_type=sa.String(length=15),
               type_=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the testable, start with STRY | DEF',
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.drop_column('testables', 'updated_at')
    op.alter_column('dev_history', 'testable_id',
               existing_type=sa.String(length=15),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='testable_id::uuid')
    op.alter_column('assignment_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('assignment_history', 'testable_id',
               existing_type=sa.String(length=15),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='testable_id::uuid')
    op.drop_column('assignment_history', 'updated_at')

    # Recreate foreign keys
    op.create_foreign_key('assignment_history_testable_id_fkey', 'assignment_history', 'testables', ['testable_id'], ['id'])
    op.create_foreign_key('dev_history_testable_id_fkey', 'dev_history', 'testables', ['testable_id'], ['id'])
    # ### end Alembic commands ###
